### ISSUE TITLE
Repository empty?

### ISSUE THREAD

**Issue by lianstuder** [timo-cmd2/nasm#1]

**Comment by lianstuder** [comment]
I want NASM asap

**Comment by timo-cmd2** [comment]
Yes, noob. Everything I have on gh is wip so don’t expect anything noob

**Comment by lianstuder** [comment]
chill bruh don't call me noob u noob

**Comment by timo-cmd2** [comment]
xD

**Comment by krissemicolon** [comment]
github beef?? haha

**Comment by timo-cmd2** [comment]
du au no bruh xDDD

**Comment by timosarkar** [comment]
Tbh my gh is dead now. More important things going on rn
